#!/bin/bash
# Simplified Daily Repository Health Check
GH_USER="srinivas486"
OUTPUT_FILE="/root/.openclaw/health-check/report.md"
TOKEN=$(cat ~/.git-credentials | sed 's|https://[^:]*:\([^@]*\)@github.com|\1|')

echo "# Daily Repository Health Check" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Generated: $(date '+%Y-%m-%d %H:%M %Z')" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Get all repos
REPOS=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/users/$GH_USER/repos?per_page=100" | grep -o '"full_name": "[^"]*"' | cut -d'"' -f4)

TOTAL_REPOS=0; TOTAL_ISSUES=0; TOTAL_PRS=0

for REPO in $REPOS; do
    TOTAL_REPOS=$((TOTAL_REPOS + 1))
    
    DATA=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO")
    ISSUES=$(echo "$DATA" | grep -o '"open_issues_count": [0-9]*' | head -1 | grep -o '[0-9]*$')
    ISSUES=${ISSUES:-0}
    TOTAL_ISSUES=$((TOTAL_ISSUES + ISSUES))
    
    LAST_PUSH=$(echo "$DATA" | grep -o '"pushed_at": "[^"]*"' | cut -d'"' -f4 | head -1)
    [ -n "$LAST_PUSH" ] && LAST_PUSH=$(date -d "$LAST_PUSH" '+%Y-%m-%d' 2>/dev/null) || LAST_PUSH="N/A"
    
    OPEN_PRS=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO/pulls?state=open&per_page=1" -I 2>/dev/null | grep -i "^x-total-count:" | grep -o '[0-9]*' || echo "0")
    OPEN_PRS=${OPEN_PRS:-0}
    TOTAL_PRS=$((TOTAL_PRS + OPEN_PRS))
    
    PRIVATE=$(echo "$DATA" | grep -q '"private": true' && echo "Private" || echo "Public")
    
    echo "## $REPO" >> "$OUTPUT_FILE"
    echo "- **Status**: $PRIVATE" >> "$OUTPUT_FILE"
    echo "- **Open Issues**: $ISSUES" >> "$OUTPUT_FILE"
    echo "- **Open PRs**: $OPEN_PRS" >> "$OUTPUT_FILE"
    echo "- **Last Push**: $LAST_PUSH" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    echo "Scanned: $REPO"
done

echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Summary" >> "$OUTPUT_FILE"
echo "- **Total Repos**: $TOTAL_REPOS" >> "$OUTPUT_FILE"
echo "- **Total Open Issues**: $TOTAL_ISSUES" >> "$OUTPUT_FILE"
echo "- **Total Open PRs**: $TOTAL_PRS" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "*Report generated by OpenClaw Health Check*" >> "$OUTPUT_FILE"

echo "Done: $TOTAL_REPOS repos, $TOTAL_ISSUES issues, $TOTAL_PRS PRs"
